# Site wide configuration

title:            Răzvan Petruescu
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Răzvan Petruescu
  avatar: RP.png
  bio: "Functional programming for the masses"
  email:
  disqus-shortname: blog-petruescu
  twitter: razvanpetruescu
  facebook: #username
  google:
    plus: RazvanPetruescu
    analytics: UA-69349190-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  bitbucket: razvan_petruescu
  stackoverflow: 1557686/razvan-petruescu
  linkedin: razvanpetruescu
  #cv: OmXEYK
  coursera: 3ffd86bbc63900998ce794c1e5712b83
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
